on:
  push:
     branches: master
jobs:
   build-and-deploy:
	  runs-on: ubuntu-latest
 	
	  steps:
	    - name: Checkout code
	      uses: actions/checkout@v2
       
      - name: Setup Nodejs
	      uses: actions/setip-nodejs@v4
 	      with:
		          node-version:'20.x' 

	    - name: Install dependency
	      run: |
		    sudo apt-get update
		    npm install

	    - name: Build the code
	      run: npm run build
