name : Deploy to server

on:
  push:
    branches: master
    
jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
            - name: Checkout code
              uses: actions/checkout@v2
              
            - name: Set up nodejs
              uses: actions/setup-node@v4
              with: 
                  node-version:'20.x'

            - name: Install node and npm
              runs: |
                    sudo apt update
                    sudo npm install
                    
